#!/usr/bin/python3

import sys
import os
import git
import datetime

from yggdrasil import *
from ui_helpers import *

import pygame
from pygame.locals import *
from OpenGL.GL import *
from OpenGL.GLU import *

edges = list()
nodes = dict()


def shorthash(commit) :
    return str(commit)[0:5]

def shortmsg(commit) :
    return str(commit.message).split('\n',1)[0]

repodir = os.getcwd()
if len(sys.argv) == 2 :
    repodir = sys.argv[1]

print("git-3d has started for" + repodir)

# load git repository
repo = git.Repo(repodir)
assert not repo.bare

# load all commits
commit_list = list(repo.iter_commits())
commit_list.sort(key=lambda c: c.committed_datetime.timestamp())
pos = 0

print("Heads:")
heads = list()
for head in repo.heads :
    print(str(head))
    heads.append(str(head.commit))

print("Commit list:")
for c in commit_list :
    print(shorthash(c) + ": " + shortmsg(c))
    ts = int(c.committed_datetime.timestamp())

    ygg_c = YggCommit(c)
    ygg_c.position = (0,0,pos)
    if str(c) in heads :
        ygg_c.setColorFromString("DAC148")
    nodes[str(c)] = ygg_c
    pos = pos + 1

# add edges between commits
for c in commit_list :
    for p in c.parents :
        edges.append((str(p), str(c)))

print("Showing Graph:")
pygame.init()
pygame.display.set_mode((800, 800), DOUBLEBUF | OPENGL)
gluPerspective(90, 1, 0.1, 100)
glTranslatef(0,0, -10)
glRotatef(25, 2, 1, 0)

redraw = True

clock = pygame.time.Clock()
while True:
    clock.tick(30)
    redraw |= handle_pygame_events()
    if not redraw :
        continue

    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)

    for node, ygg_c in nodes.items() :
        ygg_c.draw()

    glLineWidth(5)
    glBegin(GL_LINES)
    for edge in edges :
        for vertex in edge :
            glVertex3fv(nodes[vertex].position.toTuple())
    glEnd()
    pygame.display.flip()
    redraw = False